on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        required: true
      target:
        type: string
        required: true
      image:
        type: string
        required: true
      push:
        type: boolean
        required: false
        default: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          target: ${{ inputs.target }}
          tags: ${{ inputs.image }}:${{ steps.date.outputs.date }}
          platforms: linux/amd64
